---
# archivo de tareas para roles / osp-instance-delete
  - nombre : Obtener información de instancia
    os_server_facts :
      nube : ospcloud
      region_name : RegionOne
    registrarse : r_os_servers

  - nombre : eliminar instancias
    os_server :
      nombre : " {{item.name}} "
      estado : ausente
      delete_fip : sí
    con_artículos :
      - " {{r_os_servers.ansible_facts.openstack_servers}} "
