---
# tasks file for base-config
# Initial, common, system setup steps
- name: clean the repository
  shell: yum clean all

 


- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

 

- name: Install EPEL repos 
  yum:
   name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
   state: present 

 

- name: setup hostname
  hostname:
    name: "{{ inventory_hostname }}"

 

- name: install base tools and packages
  yum:
   name: "{{ item }}" 
   state: latest
  with_items:
   - httpie
   - python-pip
